version: 2
jobs:
  build:
    docker:
      - image: turbinelabs/build-common:0.9.19.7
        cmd: ["/bin/bash"]

    working_directory: "~/"

    environment:
      - PROJECT: test
      - TEST_RUNNER_OUTPUT: /tmp/test-results/testrunner

    steps:
      - checkout:
          path: $GOPATH/src/github.com/turbinelabs/$PROJECT

      - run: env | sort

      - run:
          name: install deps
          command: go get github.com/turbinelabs/$PROJECT/...

      - run:
          name: install testrunner
          command: |
            go get github.com/turbinelabs/test/testrunner
            go install github.com/turbinelabs/test/testrunner

      - run:
          name: run tests
          command: bash code_coverage.sh $(go list github.com/turbinelabs/$PROJECT/... | grep -v /vendor/)
              
      - run: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: /tmp/test-results
