version: 2
jobs:
  build:
    docker:
      - image: turbinelabs/build-common:0.9.19.7
        cmd: ["/bin/bash"]

    working_directory: "~/"

    environment:
      - PROJECT: test
      - TEST_RUNNER_OUTPUT: /tmp/test-results/testrunner

    steps:
      - checkout:
          path: $GOPATH/src/github.com/turbinelabs/$PROJECT

      - run: env | sort

      - run:
          name: install deps
          command: go get github.com/turbinelabs/$PROJECT/...

      - run:
          name: install testrunner
          command: |
            go get github.com/turbinelabs/test/testrunner
            go install github.com/turbinelabs/test/testrunner

      - run:
          name: run tests
          command: |
            function die() {
              echo $*
              exit 1
            }

            # Initialize error tracking
            ERROR=""
            COVERAGE_FILE=coverage.txt
            TMP_FILE=coverage_tmp.txt

            rm -rf $COVERAGE_FILE
            touch $COVERAGE_FILE
            rm -rf $TMP_FILE

            # Test each package and append coverage profile info to coverage.txt
            for PKG in $(go list github.com/turbinelabs/$PROJECT/... | grep -v /vendor/); do
                touch $TMP_FILE
                go test $GO_TEST_RUNNER \
                  -timeout $GO_TEST_TIMEOUT \
                  -covermode=count \
                  -coverprofile=$TMP_FILE \
                  $PKG || ERROR="$ERROR $PKG"

                cat $TMP_FILE | grep -v "/mock_" >> $COVERAGE_FILE
                rm -rf $TMP_FILE
            done

            if [ ! -z "$ERROR" ]
            then
                die "Encountered error for one or more packages: $ERROR"
            fi
              
      - run: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: /tmp/test-results
