version: 2
jobs:
  build:
    docker:
      - image: turbinelabs/build-common:0.9.19.7
        cmd: ["/bin/bash"]

    working_directory: "~/"

    environment:
      - PROJECT: test
      - $GOPATH: /root/go
      - FULL_PROJECT: github.com/turbinelabs/test
      - TEST_RUNNER_OUTPUT: /tmp/test-results/testrunner

    steps:
      - checkout:
          path: /go/src/$FULL_PROJECT

      - run: env | sort

      - run:
          name: install deps
          command: go get $FULL_PROJECT/...

      - run:
          name: install testrunner
          command: |
            go get github.com/turbinelabs/test/testrunner
            go install github.com/turbinelabs/test/testrunner

      - run: find $GOPATH/src

      - run:
          name: run tests
          command: |
            bash $GOPATH/src/$FULL_PROJECT/code_coverage.sh \
              $(go list $FULL_PROJECT/... | grep -v /vendor/)

      - run: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: /tmp/test-results
