version: 2
executorType: docker

containerInfo:
  - image: turbinelabs/build-common:0.9.19.3
    cmd: ["/bin/bash"]

stages:
  build:
    environment:
      - PROJECT: test
      - TEST_RUNNER_OUTPUT: /tmp/test-results/testrunner

    steps:
      - type: checkout
        path: $GOPATH/src/github.com/turbinelabs/$PROJECT

      - type: shell
        shell: /bin/bash
        command: env | sort

      - type: shell
        shell: /bin/bash
        name: install testrunner
        command: |
          go get github.com/turbinelabs/test/testrunner
          go install github.com/turbinelabs/test/testrunner

      - type: shell
        shell: /bin/bash
        name: run tests
        command: |
          go test -exec testrunner github.com/turbinelabs/$PROJECT/...

      - type: test-results-store
        path: /tmp/test-results
